name: Build

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OCaml
        uses: actions/checkout@v4
        with:
          repository: ocaml/ocaml
      - name: Configure
        run: |
          bash -xe tools/ci/actions/runner.sh configure
      - name: Build OCaml
        run: |
          MAKE_ARG=-j bash -xe tools/ci/actions/runner.sh build
      - name: Install OCaml
        run: |
          MAKE_ARG=-j bash -xe tools/ci/actions/runner.sh install
      - name: Install Deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-luatex hevea sass
      - name: Build Manual
        run: |
          MAKE_ARG=-j bash -xe tools/ci/actions/runner.sh manual
      - name: Checkout Pages
        uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages
      - name: Deploy
        working-directory: gh-pages
        run: |
          git rm '*'
          mv ../manual/src/webman/*/* .
          { echo 'User-agent: *'; echo 'Disallow: /'; } > robots.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m generate
          git push
